### ISSUE TITLE
测试中的错误

### ISSUE THREAD

**Issue by linwenjun** [tws-practice/collection-calculate-camp#17]
这一行
https://github.com/iamcoach/collection-calculate-camp/blob/master/specs/superposition_operation/own_elements_operation/subscript_is_even/calculate_median_spec.js#L10
应该为4，而不是3

**Comment by Evan-Leee** [comment]
嗯，我一会儿回去改，老师再顺带看看上次作业





-------- 原始邮件 --------
发件人：linwenjun <notifications@github.com>
时间：周日 11月22日 11:37
收件人：iamcoach/collection-calculate-camp <collection-calculate-camp@noreply.github.com>
主题：[collection-calculate-camp] 测试中的错误 (#17)

**Comment by fgcui1204** [comment]
@linwenjun 
`var collection_a = [1, 2, 3, 4, 5, 6];`

数组是从第0个元素开始的，这个集合中第偶数个元素的集合为[1,3,5]，所以中位数是3

**Comment by jtong** [comment]
@fgcui1204  
不是这样的，第几个是从1开始计数的，不然整个题库里的描述就冲突了： 

https://github.com/iamcoach/collection-calculate-camp/commit/67cb6b99c11f26f8f9c6ee3d979cdb914bad417d

https://github.com/iamcoach/collection-calculate-camp/commit/1e33d10bae48ede0255dad5fad1e22d331301443
